apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techlab-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dhomi/k8s-gitops-argocd.git'
    # repoURL: 'file:///Users/adhomi/Documents/REPO/WORK/LEARN/roadmap/gitOps-argoCD/hello-world'
    path: techlab
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true