apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-techlab
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: slack-notification
          image: curlimages/curl
          command:
            - curl
            - http://localhost:8081'
      restartPolicy: Never
  backoffLimit: 2