apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-html
  namespace: argocd
data:
  index.html: |
    <html>
    <head><title>GitOps - K8s/ArgoCD - TechLab</title></head>
    <body>
      <h1>Hartelijke groet'n van Techlab in Kubernetes!</h1>
      <p>HTML komt uit de ConfigMap. - 03.10.2025 - 10:59 </p>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: argocd
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          env:
            - name: VERSION
              value: "versie 3-10" # vervang dit met je eigen versie
            - name: TAG
              value: "techlab-3-10"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html-volume
          configMap:
            name: custom-html

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # service port
      targetPort: 80  # container port
      nodePort: 30081 # pick a port in 30000-32767