apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-html
data:
  index.html: |
    <html>
    <head><title>GitOps - K8s/ArgoCD - TechLab</title></head>
    <body>
      <h1>Hartelijke groet'n van Techlabin Kubernetes!</h1>
      <p>HTML komt uit de ConfigMap.</p>
      <p>tag:23-09 10:46</p>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html-volume
          configMap:
            name: custom-html
