apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: init-html
        image: busybox
        env:
        - name: VERSION
          value: "1.0.0"  # Hier kun je eventueel via env komen of uit ConfigMap
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        command:
        - /bin/sh
        - -c
        - |
          cat /usr/share/nginx/html/index.html.template | sed "s/{{VERSION}}/$VERSION/g" > /usr/share/nginx/html/index.html
      volumes:
      - name: html-volume
        configMap:
          name: custom-html