apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-html
data:
  index.html: |
    <html>
    <head><title>GitOps - K8s/ArgoCD - TechLab</title></head>
    <body>
      <h1>Hartelijke groet'n van Techlabin Kubernetes!</h1>
      <p>HTML komt uit de ConfigMap.</p>
      <p>tag:22-09 16:14.</p>
    </body>
    </html>

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-custom
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html
  volumes:
  - name: html-volume
    configMap:
      name: custom-html